apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: services-config
  namespace: {{ .Values.global.namespace }}
data:
  services.yaml: |
    - service: defaultservice
      kind: yrlib
      description: this is the default service
      functions:
        default:
          timeout: 900
          cpu: 500
          memory: 500
          runtime: python3.11
          concurrentNum: 20
        py:
          timeout: 900
          cpu: 500
          memory: 500
          runtime: python3.11
          concurrentNum: 20
        java:
          timeout: 900
          cpu: 500
          memory: 500
          runtime: java1.8
          concurrentNum: 20
        cpp:
          timeout: 900
          cpu: 500
          memory: 500
          runtime: cpp11
          concurrentNum: 20